Warning: t_min calculated by A_THRES is first curve value; loadcase Head X Acceleration Analysis, signal head_x_accel.
Warning: t_max calculated by B_THRES is last curve value; loadcase Head X Acceleration Analysis, signal head_x_accel.
Error: End time of corridor 1 in file C:\Users\kryst\Desktop\THESIS\Data_Analysis\Python_Files\H_CORA_Analysis\Simulation_1\data\exp_stdev_head_x_accel t_end = 0.298500 < t_max = 250.000000
