Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Signal type in: 'ccel' unknown
Warning: Number of supporting points before t_min reduces time shift from       39 to        0 for signal: head_y_rot_accelloadcase: Head Y Angular Acceleration Analysis !
