Warning: t_max calculated by B_THRES is last curve value; loadcase Head Z Acceleration Analysis, signal head_z_accel.
Warning: Number of supporting points before t_min reduces time shift from       42 to        0 for signal: head_z_accelloadcase: Head Z Acceleration Analysis !
Warning: Number of supporting points after t_max reduces time shift from       42 to       37 for signal: head_z_accelloadcase: Head Z Acceleration Analysis !
